Areas/Contabilidad/Controllers/TransaccionContableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRUEBA_UX_UI__NEOCONT_.Areas.Contabilidad.Controllers
{
    public class TransaccionContableController : Controller
    {

        public ActionResult IngresoAsientosContablesManuales()
        {
            ViewBag.Title = "Ingreso de Asientos Contables Manuales";
            ViewBag.Message = "IngresoAsientosContablesManuales";
            return View();
        }

        public ActionResult SolicitudIngresoAsientoOperativos()
        {
            ViewBag.Message = "SolicitudIngresoAsientoOperativos";
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRUEBA_UX_UI__NEOCONT_.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRUEBA_UX_UI__NEOCONT_.Controllers
{
    public class SharedController : Controller
    {
        public ActionResult Placeholder()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }

        public ActionResult HelpCenter()
        {
            return View();
        }
    }
}

Areas/Contabilidad/Views/TransaccionContable/SolicitudIngresoAsientoOperativos.cshtml
@{
    ViewBag.CurrentDate = DateTime.Now.ToString("yyyy/MM/dd");


    var date = DateTime.Now;

    if (date.DayOfWeek == DayOfWeek.Saturday)
    {
        date = date.AddDays(2);
    }
    else if (date.DayOfWeek == DayOfWeek.Sunday)
    {
        date = date.AddDays(1);
    }

    ViewBag.AccountingDate = date.ToString("yyyy/MM/dd");

    ViewBag.User = "psolis";
}
<ol class="breadcrumb modern-breadcrumb">
    <li><a>Contabilidad</a></li>
    <li><a>Transacción Contable</a></li>
    <li class="active">Solicitud Ingreso Asientos Operativos</li>
</ol>

@*Panel*@
<div class="panel panel-modern">
    <div class="panel-body">
        <form>
            <div class="row">

                <div class="col-md-3 form-group">
                    <label>Fecha Contable</label>
                    <input type="text" class="form-control" value="@ViewBag.AccountingDate" disabled />
                </div>

                <div class="col-md-3 form-group">
                    <label>Departamento</label>
                    <select class="form-control" id="departamentoOperativo">
                        <option value="AC">AC - ACCIONES</option>
                        <option value="CC">CC - CRÉDITO</option>
                        <option value="FI">FI - FINANZAS</option>
                    </select>
                </div>

                <div class="col-md-3 form-group">
                    <label>Oficina</label>
                    <select class="form-control" id="oficinaOperativo">
                        <option>001 - MATRIZ</option>
                        <option>002 - SUCURSAL NORTE</option>
                        <option>003 - SUCURSAL SUR</option>
                    </select>
                </div>

                <div class="col-md-3 form-group">
                    <label>Descripción</label>
                    <input type="text" class="form-control" id="descripcionOperativo" disabled />
                </div>
            </div>
        </form>
    </div>

    <div class="table-responsive detalle-asientosOperativos">
        <table class="table table-bordered table-hover table-modern">
            <thead>
                <tr>
                    <th>Cuenta</th>
                    <th>Descripción Cuenta</th>
                    <th>Tipo</th>
                    <th>Moneda</th>
                    <th>Motivo</th>
                    <th>Producto</th>
                    <th>C. Costo</th>
                    <th>Of. Mov</th>
                    <th>Desc. Proceso</th>
                    <th>Prueba Detpal.</th>
                    <th>Identificación</th>
                    <th>Cliente</th>
                    <th>Doc / Cod</th>
                    <th class="text-right">Valor MN</th>
                    <th class="text-right">Valor ME</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <select class="form-control tipo-selector">
                            <option value="">---</option>
                            <option value="110101">110101</option>
                            <option value="220202">220202</option>
                            <option value="330303">330303</option>
                        </select>
                    </td>
                    <td><input type="text" class="form-control" /></td>
                    <td>
                        <select class="form-control">
                            <option value="1">CREDITO</option>
                            <option value="2">DEBITO</option>
                        </select>
                    </td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td>
                        <select class="form-control">
                            <option>001 - MATRIZ</option>
                            <option>002 - SUCURSAL NORTE</option>
                            <option>003 - SUCURSAL SUR</option>
                        </select>
                    </td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="text" class="form-control" /></td>
                    <td><input type="number" class="form-control text-right" /></td>
                    <td><input type="number" class="form-control text-right" /></td>
                    <td class="text-center">
                        <button type="button" class="btn btn-xs btn-magenta"><i class="glyphicon glyphicon-trash"></i></button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Tabla de Totales -->
    <div class="table-responsive">
        <table class="table table-bordered table-modern" style="max-width: 400px; margin: 25px 20px">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-right">TOTAL MN</th>
                    <th class="text-right">TOTAL ME</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>DÉBITO</strong></td>
                    <td id="totalDebitoMN" class="text-right">0.00</td>
                    <td id="totalDebitoME" class="text-right">0.00</td>
                </tr>
                <tr>
                    <td><strong>CRÉDITO</strong></td>
                    <td id="totalCreditoMN" class="text-right">0.00</td>
                    <td id="totalCreditoME" class="text-right">0.00</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="text-left" style="padding: 0 25px 20px">
        <button type="button" class="btn btn-magenta" id="btnGrabarAsientoOperativo">
            <i class="glyphicon glyphicon-floppy-disk"></i> Grabar Asiento
        </button>
    </div>
</div>

@*Modal Eliminar*@
<div class="modal fade" id="confirmarEliminarModalOperativo" tabindex="-1" role="dialog" aria-labelledby="confirmarEliminarLabelOperativo">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header" style="background-color: var(--color-magenta); color: white; border-radius: 8px 8px 0 0;">
                <h4 class="modal-title" id="confirmarEliminarLabelOperativo">
                    Confirmar eliminación
                </h4>
            </div>

            <div class="modal-body text-center mb-0">
                <p class="mensaje-eliminar mb-0">¿Está seguro que desea eliminar este detalle del asiento?</p>
            </div>

            <div class="modal-footer text-center">
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    <i class="glyphicon glyphicon-remove"></i> Cancelar
                </button>
                <button type="button" class="btn btn-magenta" id="btnConfirmarEliminar">
                    <i class="glyphicon glyphicon-trash"></i> Borrar
                </button>
            </div>
        </div>
    </div>
</div>

@*Modal Exito*@
<div class="modal fade" id="asientoExitoModalOperativo" tabindex="-1" role="dialog" aria-labelledby="asientoExitoLabelOperativo">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header" style="background-color: var(--color-magenta); color: white; border-radius: 8px 8px 0 0;">
                <h4 class="modal-title" id="asientoExitoLabelOperativo">
                    Éxito
                </h4>
            </div>

            <div class="modal-body text-center mb-0">
                <p class="mensaje-eliminar mb-0">El asiento contable ha sido guardado con éxito. Número de Asiento: <strong id="numeroAsientoExito"></strong></p>
            </div>

            <div class="modal-footer text-center">
                <button type="button" class="btn btn-magenta" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

@*Modal Mensajes*@
<div class="modal fade" id="mensajeModal" tabindex="-1" role="dialog" aria-labelledby="mensajeModalLabel">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">

            <div class="modal-header" style="background-color: var(--color-magenta); color: white; border-radius: 8px 8px 0 0;">
                <h4 class="modal-title" id="mensajeModalLabel">
                    Aviso
                </h4>
            </div>

            <div class="modal-body text-center mb-0">
                <p id="mensajeModalTexto" class="mensaje-eliminar mb-0"></p>
            </div>

            <div class="modal-footer text-center">
                <button type="button" class="btn btn-magenta" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/HelpCenter.cshtml
@{
    ViewBag.Title = "Centro de Ayuda";
    ViewBag.Message = "Accede a guías, preguntas frecuentes y soporte para resolver tus dudas de forma rápida y sencilla.";
}

<div class="welcome-container">
    <div class="welcome-content">
        <h1 class="welcome-title">@ViewBag.Title</h1>

        <div class="panel panel-modern">
            <div class="panel-body">
                <p>
                    @ViewBag.Message
                </p>
                
            </div>
        </div>
    </div>
</div>

Views/Shared/NotFound.cshtml
<div style="display: flex; justify-content: center; align-items: center; height: 70vh; text-align: center;">
    <div >
            <h1>🔎 Página no encontrada</h1>
            <p>La opción que intenta acceder no existe o ya no está disponible.</p>
            <a href="@Url.Action("Placeholder","Shared")" class="btn btn-primary">Volver al inicio</a>
    </div>
</div>

Views/Shared/Placeholder.cshtml
@{
    ViewBag.Title = "Bienvenido a NEOCONT";
}

<div class="welcome-container">
    <div class="welcome-content">
        <h1 class="welcome-title">@ViewBag.Title</h1>

        <div class="panel panel-modern">
            <div class="panel-body">
                <p>
                    Seleccione una opción del menú superior para comenzar a trabajar.
                    <br />
                    Si necesita asistencia, diríjase al
                    <a href="@Url.Action("HelpCenter", "Shared", new { area = "" })" class="help-link">
                        <i class="glyphicon glyphicon-question-sign"></i> <strong>Centro de Ayuda</strong>
                    </a>.
                </p>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "NEOCONT";
    ViewBag.User = "Paulo Solis Andrade";
    ViewBag.Office = "MATRIZ – EDIFICIO PRINCIPAL";
    ViewBag.CurrentDate = DateTime.Now.ToString("dddd, dd 'de' MMMM 'de' yyyy", new System.Globalization.CultureInfo("es-ES"));


    var date = DateTime.Now;

    if (date.DayOfWeek == DayOfWeek.Saturday)
    {
        date = date.AddDays(2);
    }
    else if (date.DayOfWeek == DayOfWeek.Sunday)
    {
        date = date.AddDays(1);
    }

    ViewBag.AccountingDate = date.ToString(
        "dddd, dd 'de' MMMM 'de' yyyy",
        new System.Globalization.CultureInfo("es-ES")
    );
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
</head>

<body>
    <header class="navbar navbar-inverse navbar-static-top" role="banner" style="background-color: #BC157C; border: none; ">
        <div class="container-fluid">
            <div class="row" style="display: flex; align-items: center; padding: 10px 20px 0px;">

                <div class="col-xs-4 col-sm-3">
                    <a href="@Url.Action("Placeholder", "Shared", new { area = "" })">
                        <img src="~/Content/img/logo_bg_white.png" alt="Banco Guayaquil" style="height:40px;">
                    </a>
                </div>

                <div class="col-xs-4 col-sm-6 text-center">
                    <a href="@Url.Action("Placeholder", "Shared", new { area = "" })" style="text-decoration:none; color:white;">
                        <h1 style="color:white; font-weight:700; margin:0;">@ViewBag.Title</h1>
                    </a>
                </div>


                <div class="col-xs-4 col-sm-3 text-right" style="color:white; font-size:12px; line-height:1.4;">
                    <div><strong>@ViewBag.User</strong></div>
                    <div><strong>@ViewBag.Office</strong></div>
                    <div><strong>@ViewBag.CurrentDate</strong></div>
                </div>

            </div>
        </div>

        <nav class="navbar navbar-default" style="margin-bottom: 0; background-color: #BC157C; border: none; padding: 0px 20px 0px 5px; ">
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Placeholder", "Shared", new { area = "" })">Inicio</a></li>
                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Administración</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Contabilidad
                        </a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu">
                                <a>Transacción Contable</a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Plan de Cuentas</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta de Movimientos Contables</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta de Mayor Contable (Mensual)</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta de Saldos Diarios y Promedios de Cuentas Contables</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta de Asientos Contables</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta - Ruteo y Aprobación de Asientos Manuales</a></li>
                                    <li>
                                        <a href="@Url.Action("IngresoAsientosContablesManuales", "TransaccionContable", new { area = "Contabilidad" })" class="nav-link">
                                            Ingreso de Asientos Contables Manuales
                                            <span class="dot-blink"></span>
                                        </a>
                                    </li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Ingreso de Asientos Contables (Plantilla Masiva)</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Creación de Modelos de Asientos (Plantilla Manual)</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Ingreso de Asientos Contables (Plantilla Manual)</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Mayorización de Asientos Contables</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Desmayorización de Asientos Contables</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Consulta Contable por Centro de Costos</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Cuadres de Interfaces</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Factor Conversión</a></li>
                                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Actualización de Saldos</a></li>
                                    <li>
                                        <a href="@Url.Action("SolicitudIngresoAsientoOperativos", "TransaccionContable", new { area = "Contabilidad" })" class="nav-link">
                                            Solicitud Ingreso Asientos Operativos
                                            <span class="dot-blink"></span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Bancos</a></li>
                    <li><a href="@Url.Action("NotFound", "Shared", new { area = "" })">Cuadre Contable</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a class="no-hover">@ViewBag.AccountingDate</a></li>
                    <li><a href="@Url.Action("HelpCenter", "Shared", new { area = "" })"><i class="glyphicon glyphicon-question-sign"></i> Centro de Ayuda</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <div class=" body-content">
        @RenderBody()
    </div>
</body>
</html>

@Scripts.Render("~/Scripts/jquery")
@Scripts.Render("~/Scripts/bootstrap")
@Scripts.Render("~/Scripts/js")
@RenderSection("scripts", required: false)